#!/bin/bash

set -e

# cargo test --test web_authentication -- --nocapture

# cargo test --test storage -- --nocapture

cargo run -- -c ./.env.e2e &

node_modules/.bin/wait-on -t 600000 -i 250 -w 250 https://127.0.0.1:5443/api/liveness && echo "API is up"

export NODE_TLS_REJECT_UNAUTHORIZED=0

turbo run wasm-pack

(turbo test:e2e) || TEST_EXIT_CODE=$?

kill -9 $!

exit $TEST_EXIT_CODE
