#!/bin/bash

set -e

cargo test --test web_authentication -- --nocapture

cargo test --test storage -- --nocapture

cargo run -- -c ./.env.e2e &

node_modules/.bin/wait-on -t 60000 -i 250 -w 250 http://127.0.0.1:4554/api/liveness

(turbo test:e2e) || TEST_EXIT_CODE=$?

kill -9 $!

exit $TEST_EXIT_CODE
