#!/bin/bash

set -e

rm -rf /tmp/data

cargo run -- -c .env.e2e &

node_modules/.bin/wait-on -t 600000 -i 250 -w 250 https://127.0.0.1:5443/api/liveness && echo "API is up"

export ENV_FILE="../.env.e2e"
(yarn workspace @hoodik/web test:e2e) || TEST_EXIT_CODE=$?

kill -9 $!

exit $TEST_EXIT_CODE
