//! Cross-runtime fixture suite for `cryptfns::asn1`. The committed `.der`
//! bytes are the contract that the WASM and Flutter FFI builds also verify
//! against — see `web/tests/shares/asn1_fixtures.test.ts` and
//! `hoodik-app/integration_test/e2e/asn1_fixtures_test.dart`.
//!
//! Set `REGEN_FIXTURES=1` to overwrite the committed `.der` files from the
//! current encoder output, then commit the regenerated bytes.

mod fixtures;

use std::path::PathBuf;

use cryptfns::asn1::{
    encode_audit_event_sig_input_v1, encode_audit_event_v1, encode_entries_v1,
    encode_folder_member_list_v1, encode_member_sig_v1, encode_share_request_v1,
    AUDIT_EVENT_SIG_V1_PREFIX, AUDIT_EVENT_V1_PREFIX, FOLDER_LIST_V1_PREFIX, MEMBER_SIG_V1_PREFIX,
    SHARE_REQUEST_V1_PREFIX,
};
use cryptfns::hex;
use cryptfns::rsa;

fn fixtures_path(name: &str) -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests");
    p.push("fixtures");
    p.push(name);
    p
}

fn maybe_regen(name: &str, current: &[u8]) {
    if std::env::var("REGEN_FIXTURES").is_ok() {
        std::fs::write(fixtures_path(name), current).expect("writing regenerated fixture");
    }
}

#[test]
fn share_request_v1_matches_fixture() {
    let bytes = encode_share_request_v1(&fixtures::share_request_v1()).unwrap();
    maybe_regen("share_request_v1.der", &bytes);
    assert_eq!(
        bytes,
        fixtures::SHARE_REQUEST_DER,
        "share_request_v1 encoder drifted from committed fixture"
    );
}

#[test]
fn member_sig_v1_matches_fixture() {
    let bytes = encode_member_sig_v1(&fixtures::member_sig_v1()).unwrap();
    maybe_regen("member_sig_v1.der", &bytes);
    assert_eq!(
        bytes,
        fixtures::MEMBER_SIG_DER,
        "member_sig_v1 encoder drifted from committed fixture"
    );
}

#[test]
fn audit_event_v1_matches_fixture() {
    let bytes = encode_audit_event_v1(&fixtures::audit_event_v1()).unwrap();
    maybe_regen("audit_event_v1.der", &bytes);
    assert_eq!(
        bytes,
        fixtures::AUDIT_EVENT_DER,
        "audit_event_v1 encoder drifted from committed fixture"
    );
}

#[test]
fn folder_member_list_v1_matches_fixture() {
    let bytes = encode_folder_member_list_v1(&fixtures::folder_member_list_v1()).unwrap();
    maybe_regen("folder_member_list_v1.der", &bytes);
    assert_eq!(
        bytes,
        fixtures::FOLDER_MEMBER_LIST_DER,
        "folder_member_list_v1 encoder drifted from committed fixture"
    );
}

#[test]
fn audit_event_sig_input_v1_matches_fixture() {
    let bytes = encode_audit_event_sig_input_v1(&fixtures::audit_event_sig_input_v1()).unwrap();
    maybe_regen("audit_event_sig_input_v1.der", &bytes);
    assert_eq!(
        bytes,
        fixtures::AUDIT_EVENT_SIG_INPUT_DER,
        "audit_event_sig_input_v1 encoder drifted from committed fixture"
    );
}

#[test]
fn signature_verifies_against_received_bytes() {
    // The server verifies signatures over the bytes the sender wrote on the
    // wire — never against a re-encoded copy. This test exercises that
    // sign-what-you-send invariant for every v1 domain prefix and asserts
    // that flipping one byte of the payload breaks verification.
    let private = rsa::private::generate().expect("RSA-2048 keygen");
    let private_pem = rsa::private::to_string(&private).unwrap();
    let public = rsa::public::from_private(&private).unwrap();
    let public_pem = rsa::public::to_string(&public).unwrap();

    let payloads: Vec<(&[u8], Vec<u8>)> = vec![
        (
            SHARE_REQUEST_V1_PREFIX,
            encode_share_request_v1(&fixtures::share_request_v1()).unwrap(),
        ),
        (
            MEMBER_SIG_V1_PREFIX,
            encode_member_sig_v1(&fixtures::member_sig_v1()).unwrap(),
        ),
        (
            AUDIT_EVENT_V1_PREFIX,
            encode_audit_event_v1(&fixtures::audit_event_v1()).unwrap(),
        ),
        (
            AUDIT_EVENT_SIG_V1_PREFIX,
            encode_audit_event_sig_input_v1(&fixtures::audit_event_sig_input_v1()).unwrap(),
        ),
        (
            FOLDER_LIST_V1_PREFIX,
            encode_folder_member_list_v1(&fixtures::folder_member_list_v1()).unwrap(),
        ),
    ];

    for (prefix, payload) in payloads {
        let signing_input = sign_input(prefix, &payload);
        let signature = rsa::private::sign(&hex::encode(&signing_input), &private_pem)
            .expect("PSS sign succeeds");
        rsa::public::verify(&hex::encode(&signing_input), &signature, &public_pem)
            .expect("PSS verify against the bytes the signer produced");

        let mut tampered = payload.clone();
        let last = tampered.len() - 1;
        tampered[last] ^= 0x01;
        let tampered_input = sign_input(prefix, &tampered);
        assert!(
            rsa::public::verify(&hex::encode(&tampered_input), &signature, &public_pem).is_err(),
            "tampered payload bytes must fail PSS verification"
        );
    }
}

#[test]
fn entries_hash_is_stable_under_reordering() {
    let entries = fixtures::share_entries_v1();
    let a = encode_entries_v1(&entries).unwrap();
    let mut rev = entries.clone();
    rev.reverse();
    let b = encode_entries_v1(&rev).unwrap();
    assert_eq!(a, b);
}

fn sign_input(prefix: &[u8], payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(prefix.len() + payload.len());
    out.extend_from_slice(prefix);
    out.extend_from_slice(payload);
    out
}
