pub(crate) const _DEFAULT: &[u8] = include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/index.html"));
pub(crate) const _CLIENT: [(&str, &[u8]); 28] = [
("favicon-16x16.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/favicon-16x16.png"))),
("hoodik.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/hoodik.png"))),
("favicon.ico", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/favicon.ico"))),
("index.html", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/index.html"))),
("android-chrome-192x192.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/android-chrome-192x192.png"))),
("apple-touch-icon.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/apple-touch-icon.png"))),
("android-chrome-512x512.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/android-chrome-512x512.png"))),
("sw.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/sw.js"))),
("favicon-32x32.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/favicon-32x32.png"))),
("assets/VerifyEmailView-195214c5.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/VerifyEmailView-195214c5.js"))),
("assets/IndexView-8ce12f1c.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/IndexView-8ce12f1c.js"))),
("assets/metadata-d551ebdf.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/metadata-d551ebdf.js"))),
("assets/LayoutGuest.vue_vue_type_script_setup_true_lang-a307718f.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/LayoutGuest.vue_vue_type_script_setup_true_lang-a307718f.js"))),
("assets/cryptfns_bg.wasm", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/cryptfns_bg.wasm"))),
("assets/TwoFactorView-73491469.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/TwoFactorView-73491469.js"))),
("assets/PrivateKeyView-ed8a600f.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/PrivateKeyView-ed8a600f.js"))),
("assets/SectionFullScreen.vue_vue_type_script_setup_true_lang-3999be7b.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/SectionFullScreen.vue_vue_type_script_setup_true_lang-3999be7b.js"))),
("assets/IndexView-1b38e309.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/IndexView-1b38e309.js"))),
("assets/DecryptView-0c90421f.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/DecryptView-0c90421f.js"))),
("assets/KeyView-8562b72d.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/KeyView-8562b72d.js"))),
("assets/index-da16d399.css", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/index-da16d399.css"))),
("assets/main.fc21a18a.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/main.fc21a18a.js"))),
("assets/AppButton.vue_vue_type_script_setup_true_lang-d0709f93.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/AppButton.vue_vue_type_script_setup_true_lang-d0709f93.js"))),
("assets/IndexView-099c66b1.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/IndexView-099c66b1.js"))),
("assets/SetupLockScreenView-222d5e7c.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/SetupLockScreenView-222d5e7c.js"))),
("assets/cryptfns_bg-65d7988b.wasm", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/cryptfns_bg-65d7988b.wasm"))),
("assets/TwoFactorView-6b50b406.css", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/TwoFactorView-6b50b406.css"))),
("assets/AppCheckbox.vue_vue_type_script_setup_true_lang-13adc30f.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/AppCheckbox.vue_vue_type_script_setup_true_lang-13adc30f.js"))),
];
