pub(crate) const _DEFAULT: &[u8] = include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/index.html"));
pub(crate) const _CLIENT: [(&str, &[u8]); 34] = [
("favicon-16x16.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/favicon-16x16.png"))),
("hoodik.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/hoodik.png"))),
("favicon.ico", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/favicon.ico"))),
("index.html", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/index.html"))),
("android-chrome-192x192.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/android-chrome-192x192.png"))),
("apple-touch-icon.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/apple-touch-icon.png"))),
("android-chrome-512x512.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/android-chrome-512x512.png"))),
("sw.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/sw.js"))),
("favicon-32x32.png", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/favicon-32x32.png"))),
("assets/index-bc8e840f.css", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/index-bc8e840f.css"))),
("assets/TwoFactorView-02ac40a2.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/TwoFactorView-02ac40a2.js"))),
("assets/DecryptView-5c25547a.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/DecryptView-5c25547a.js"))),
("assets/LayoutGuest.vue_vue_type_script_setup_true_lang-25b1a7d9.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/LayoutGuest.vue_vue_type_script_setup_true_lang-25b1a7d9.js"))),
("assets/IndexView-8153eae3.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/IndexView-8153eae3.js"))),
("assets/main.3abb5545.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/main.3abb5545.js"))),
("assets/SetupLockScreenView-6fdd461c.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/SetupLockScreenView-6fdd461c.js"))),
("assets/AppCheckbox.vue_vue_type_script_setup_true_lang-0664aab1.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/AppCheckbox.vue_vue_type_script_setup_true_lang-0664aab1.js"))),
("assets/LinkView-9fbacdbf.css", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/LinkView-9fbacdbf.css"))),
("assets/AppButton.vue_vue_type_script_setup_true_lang-f8aa534a.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/AppButton.vue_vue_type_script_setup_true_lang-f8aa534a.js"))),
("assets/FileView-ce0a3eca.css", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/FileView-ce0a3eca.css"))),
("assets/cryptfns_bg.wasm", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/cryptfns_bg.wasm"))),
("assets/LinkView-81fc8c10.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/LinkView-81fc8c10.js"))),
("assets/IndexView-eb25b8ec.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/IndexView-eb25b8ec.js"))),
("assets/metadata-d9166e05.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/metadata-d9166e05.js"))),
("assets/cryptfns_bg-65d7988b.wasm", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/cryptfns_bg-65d7988b.wasm"))),
("assets/IndexView-520499f1.css", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/IndexView-520499f1.css"))),
("assets/VerifyEmailView-18297529.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/VerifyEmailView-18297529.js"))),
("assets/IndexView-e3897445.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/IndexView-e3897445.js"))),
("assets/TwoFactorView-6b50b406.css", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/TwoFactorView-6b50b406.css"))),
("assets/IndexView-123e68e7.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/IndexView-123e68e7.js"))),
("assets/PrivateKeyView-b12e3b10.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/PrivateKeyView-b12e3b10.js"))),
("assets/KeyView-32f23933.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/KeyView-32f23933.js"))),
("assets/SectionFullScreen.vue_vue_type_script_setup_true_lang-354724aa.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/SectionFullScreen.vue_vue_type_script_setup_true_lang-354724aa.js"))),
("assets/FileView-994d55a3.js", include_bytes!(concat!("/Users/thudik/code/hudikhq/hoodik/web/dist", "/assets/FileView-994d55a3.js"))),
];
