pub const _DEFAULT: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/index.html"));
pub const _CLIENT: [(&str, &[u8]); 29] = [
("favicon-16x16.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/favicon-16x16.png"))),
("hoodik.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/hoodik.png"))),
("favicon.ico", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/favicon.ico"))),
("index.html", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/index.html"))),
("android-chrome-192x192.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/android-chrome-192x192.png"))),
("apple-touch-icon.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/apple-touch-icon.png"))),
("hoodik.webmanifest", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/hoodik.webmanifest"))),
("workbox-208537f7.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/workbox-208537f7.js"))),
("registerSW.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/registerSW.js"))),
("android-chrome-512x512.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/android-chrome-512x512.png"))),
("sw.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/sw.js"))),
("favicon-32x32.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/favicon-32x32.png"))),
("pwa.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/pwa.js"))),
("assets/main.b591a22b.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/main.b591a22b.js"))),
("assets/constants-e97db9e8.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/constants-e97db9e8.js"))),
("assets/LockView-9e2d692e.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/LockView-9e2d692e.js"))),
("assets/cryptfns_bg-f19d6c1d.wasm", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/cryptfns_bg-f19d6c1d.wasm"))),
("assets/KeyView-7f196462.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/KeyView-7f196462.js"))),
("assets/cryptfns_bg.wasm", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/cryptfns_bg.wasm"))),
("assets/PrivateKeyView-cfde6918.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/PrivateKeyView-cfde6918.js"))),
("assets/index-c2f077f0.css", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/index-c2f077f0.css"))),
("assets/AppCheckbox.vue_vue_type_script_setup_true_lang-8838f8c8.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/AppCheckbox.vue_vue_type_script_setup_true_lang-8838f8c8.js"))),
("assets/IndexView-a54ec556.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/IndexView-a54ec556.js"))),
("assets/TwoFactorView-0d58ee26.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/TwoFactorView-0d58ee26.js"))),
("assets/SectionFullScreen.vue_vue_type_script_setup_true_lang-8de82416.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/SectionFullScreen.vue_vue_type_script_setup_true_lang-8de82416.js"))),
("assets/DecryptView-c58f6596.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/DecryptView-c58f6596.js"))),
("assets/IndexView-b84dba25.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/IndexView-b84dba25.js"))),
("assets/TwoFactorView-6b50b406.css", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/TwoFactorView-6b50b406.css"))),
("assets/SetupLockScreenView-5b4ac3b0.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/SetupLockScreenView-5b4ac3b0.js"))),
];
