pub const _DEFAULT: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/index.html"));
pub const _CLIENT: [(&str, &[u8]); 29] = [
("favicon-16x16.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/favicon-16x16.png"))),
("hoodik.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/hoodik.png"))),
("favicon.ico", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/favicon.ico"))),
("index.html", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/index.html"))),
("android-chrome-192x192.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/android-chrome-192x192.png"))),
("apple-touch-icon.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/apple-touch-icon.png"))),
("hoodik.webmanifest", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/hoodik.webmanifest"))),
("workbox-208537f7.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/workbox-208537f7.js"))),
("registerSW.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/registerSW.js"))),
("android-chrome-512x512.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/android-chrome-512x512.png"))),
("sw.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/sw.js"))),
("favicon-32x32.png", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/favicon-32x32.png"))),
("pwa.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/pwa.js"))),
("assets/TwoFactorView-0dd28f32.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/TwoFactorView-0dd28f32.js"))),
("assets/main.b7f1db2b.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/main.b7f1db2b.js"))),
("assets/SetupLockScreenView-ec6a99a2.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/SetupLockScreenView-ec6a99a2.js"))),
("assets/cryptfns_bg-f19d6c1d.wasm", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/cryptfns_bg-f19d6c1d.wasm"))),
("assets/PrivateKeyView-983605f6.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/PrivateKeyView-983605f6.js"))),
("assets/index-45eb5e7a.css", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/index-45eb5e7a.css"))),
("assets/cryptfns_bg.wasm", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/cryptfns_bg.wasm"))),
("assets/AppCheckbox.vue_vue_type_script_setup_true_lang-087ea1b5.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/AppCheckbox.vue_vue_type_script_setup_true_lang-087ea1b5.js"))),
("assets/KeyView-e9a51e6d.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/KeyView-e9a51e6d.js"))),
("assets/DecryptView-a5805ea6.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/DecryptView-a5805ea6.js"))),
("assets/IndexView-144045e8.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/IndexView-144045e8.js"))),
("assets/LockView-01cf0fcb.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/LockView-01cf0fcb.js"))),
("assets/SectionFullScreen.vue_vue_type_script_setup_true_lang-531b95f0.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/SectionFullScreen.vue_vue_type_script_setup_true_lang-531b95f0.js"))),
("assets/TwoFactorView-6b50b406.css", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/TwoFactorView-6b50b406.css"))),
("assets/constants-7d4a45ac.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/constants-7d4a45ac.js"))),
("assets/IndexView-0094640a.js", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/assets/IndexView-0094640a.js"))),
];
