name: Verify that the application version is not previously released

# When the PR is merged and hoodik/Cargo.toml is changed
# we are expecting the version of the application to also be 
# bumped. If the version is bumped, we will check that the new 
# version does not already exist in the tags because once it is 
# merged automated release will be created and app will be deployed.
on:
  pull_request:
    branches:
      - master
    paths:
      - hoodik/Cargo.toml

env:
  HANDLE: hoodik
  NAME: Hoodik

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Read the application version
        run: echo "version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select(.name == "${{ env.HANDLE }}") | .version')" >> $GITHUB_OUTPUT
        id: extract_version

      - uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with:
          tag: "v${{ steps.extract_version.outputs.version }}"

      - name: Verif the tag doesn't already exist
        run: |
          if [[ "${{ steps.checkTag.outputs.exists }}" == "true" ]]; then
            echo "Tag already exists: v${{ steps.extract_version.outputs.version }}"
            echo "This probably means that the version in the ${{ env.HANDLE }}/Cargo.toml is previously released version."
            echo "In order to merge your PR it needs to upsert the application version."
            exit 1
          fi
